### ISSUE TITLE
Mac ARM version damaged

### ISSUE THREAD

**Issue by CsatiZoltan** [otfried/ipepresenter-issues#10]
Starting the precompiled *ipepresenter-7.2.28-mac-arm.dmg* file results in the following error on macOS 12.6.8:
```
"IpePresenter" is damaged and can't be opened.
```

**Comment by otfried** [comment]
See https://github.com/otfried/ipe/issues/478

For the moment I can only advise you to download the intel version.  It also works on ARM-Macs, just a bit slower.

**Comment by CsatiZoltan** [comment]
Yes, I've just found that link a few minutes ago. Thanks. The Intel version works.
