### ISSUE TITLE
Shortcut keys of "view->Show Presentation" and "Time -> Set time" are not shown.

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipepresenter-issues#4]
Shortcut keys of "view->Show Presentation" and "Time -> Set time" are not shown in options on the top of the window.
My environment of Ipe is Windows 10 64bit.

**Comment by otfried** [comment]
I don't think Set time has a shortcut key.

**Comment by MasahiroMae** [comment]
Thanks for your early reply.
I think a shortcut key of "view->Show Presentation" is F5.
Are there any plans to set a shortcut key to "Time -> Set time" in the future?
