### ISSUE TITLE
Control command is not working when "Show Presentation" window is active.

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipepresenter-issues#5]
When "Show Presentation" window is active, "Next Page" command with "N" key or cursor keys, click link actions, "Full Screen" command with F11 key, and ... are not working.

I usually do presentations with a software laser pointer (it is the same to the mouse cursor) and in that case "Show Presentation" window is normally active not the main window.

Would you update to be able to do the same commands with the main Ipe Presenter window also on the "Show Presentation" window?

My Ipe environment is IpePresenter 7.2.17 with Windows 10 64bit.

**Comment by otfried** [comment]
Fixed in 7.2.18.

**Comment by MasahiroMae** [comment]
Thank you for your dedicated development!
