### ISSUE TITLE
Cannot use link action on presentation window in IpePresenter

### ISSUE THREAD

**Issue by MasahiroMae** [otfried/ipepresenter-issues#6]
Thanks for your work, shortcuts are now available on the presentation window.
However, link actions, e.g. Video links and URLs, are not working on the presentation window.
Is it able to make them work on the presentation window?

**Comment by otfried** [comment]
I've added clicking on the presentation window as well (just download version 7.2.18 again).

**Comment by MasahiroMae** [comment]
Thanks for your quick improvement!
