### ISSUE TITLE
doesn't display some images in pdf format, and the text on (pdf) images appears in squares

### ISSUE THREAD

**Issue by agonzal6** [otfried/ipepresenter-issues#7]
These pdf images are generated from python or stata. 
below an example:
![image](https://user-images.githubusercontent.com/47800406/94520052-78727080-01e0-11eb-84d2-4a59279ae793.png)

**Comment by otfried** [comment]
You would have to attach one of the pdf files that are not displayed correctly  if you want me to do anything about it.

**Comment by agonzal6** [comment]
Hi Otfried,
Thanks for your reply. I am attaching two pdfs, "rd_....pdf" doesn't
appear, "cost-...." appears with odd characters.
I use the latest version on windows

**Comment by otfried** [comment]
You cannot add attachments to a ticket by replying to the email.   You really have to visit

https://github.com/otfried/ipepresenter-issues/issues/7

and upload it there by dragging it into the comment field (or otherwise send the file directly to me by email).

**Comment by agonzal6** [comment]
[rd_het_overruns_rel_amount_expected_corr_mean4_overruns_rel_4.pdf](https://github.com/otfried/ipepresenter-issues/files/5299841/rd_het_overruns_rel_amount_expected_corr_mean4_overruns_rel_4.pdf)
[cost_kde_l_nl.pdf](https://github.com/otfried/ipepresenter-issues/files/5299843/cost_kde_l_nl.pdf)

Thanks, I am attaching two examples:

"rd_....pdf" doesn't appear,
 "cost-...." appears with odd characters.

I use the latest version (7.2.20) on windows

**Comment by otfried** [comment]
For your second document, after you open it in ipepresenter and press any key, ipepresenter shows you this message:

![image](https://user-images.githubusercontent.com/9983417/94684922-00fc2880-0329-11eb-876d-6135cbe09e5a.png)

Ipe does not support Type 3 (bitmapped) fonts.   It is 2020, no self-respecting PDF producing software should use such non-scalable fonts.

To avoid Type3 fonts when using matplotlib, see here: http://phyletica.org/matplotlib-fonts/

(You could also try the ipe backend for matplotlib here: https://github.com/otfried/ipe-tools/tree/master/matplotlib)

**Comment by otfried** [comment]
Your first document (`rd_het_overruns...`) uses some PDF and font features that I had not implemented (because pdftex doesn't use them).  They were easy to add, though, so here is a working version:

[ipe-7.2.20-win64.zip](https://github.com/otfried/ipepresenter-issues/files/5305663/ipe-7.2.20-win64.zip)

This support will be added in 7.2.21.
