### ISSUE TITLE
Transparent/translucent embedded PNGs

### ISSUE THREAD

**Issue by BenWiederhake** [otfried/ipepresenter-issues#9]
I'll describe these as two separate things, but since it's probably one and the same underlying issue I open only one report.

Btw, thanks for sharing ipe and ipepresenter with the world! :)

## Broken translucency (treated as alpha=255)

Steps to reproduce:
- Use a PNG with translucency (alpha between 1 and 254, I used [this one](http://pngimg.com/uploads/cloud/cloud_PNG16.png))
- Put two such PNGs over itself
Expected result: Output of ipepresenter matches how ipe, evince, and firefox display it
Actual result: The low-alpha regions get painted as if they had full alpha (i.e. 255), thereby hiding the other image

Curiously, transparency works perfectly fine with this PNG.

## Broken transparency (treated as alpha=255)

Steps to reproduce: 
- Use a PNG with transparent regions (alpha = 0, I used [this one](https://pluspng.com/img-png/png-lupe-png-file-svg-980.png))
- Include this image somewhere, and have text present, too (in my case: the page title). Text and image should logically intersect.
Expected result: Since the image has alpha=0 where it overlaps the text, the text is visible perfectly fine.
Actual result: The text is only partially visible, as if the alpha=0 regions were painted as white.

**Comment by otfried** [comment]
Somehow surprisingly, these were actually two entirely different problems.

Both are now fixed in 7.2.24.
